заголовок нового проекта
dl-academy-edu/sp-kudryavtsev-alexander pull request #4
Opened 2020-01-20 14:15 UTC by Aleksandr-dl

1ыы

2020-01-22 18:42 UTC, SergeyPechinov requested changes
Есть повторные правки, не стал писать тоже самое, пройдись по коду внимательно, и нужно расставить классы везде (каждый элемент должен иметь класс)

2020-01-22 18:42 UTC, SergeyPechinov commented on index.html
> +      <a class="poster-link pourple-link" href="#"> EXPLORE NOW </a>
Тут либо article поменять на другую обертку(p или div), либо обернуть это все в article. Это же слайдер, сейчас просто реализован 1 слайд

2020-01-22 18:42 UTC, SergeyPechinov commented on index.html
> +    <section class="about purchase">
если в название класса ставить пробел, то будет 2 класса. между слов используй "-"

2020-01-22 18:42 UTC, SergeyPechinov commented on index.html
> +      <a class="Credit"></a>
в названиях классов не должно быть больших букв

2020-01-28 16:18 UTC, SergeyPechinov requested changes

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +      <a class="credit"></a>
если у атрибута a нет href мы не можем на него попасть с помощью клавиатуры

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +      <h3 class="design-Life-Kids"Design Life Kids></h3>
тут ошибка в строке

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +     <h3 class="contacts"Contacts></h3>
тут ошибка в строке

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +        </form>
1. 2 закрывающихся тега формы
2. join нужно оборачивать не в sub, а в button type="submit".
 _(Тег sub определяет текст в виде нижнего индекса. Нижней индекс выглядит как символ под строкой. Подобный текст может быть использован в химических формулах: H2O.),_

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +    </section>
1. нужно разметить блок, а карту вставить картинкой
2. в section обязательно должен присутствовать заголовок h2-h6, если его нет на макете, можно его разметить но сделать невидимым, либо использовать другой тег, если это возможно

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +      <nav>
не нужно оборачивать весь footer в nav, а обернуть только нужные места

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +       <ul>
ul не может содержать что-то кроме li

2020-01-28 16:18 UTC, SergeyPechinov commented on index.html
> +        <a class="footer-navigation" href="#"> Navigation </a>
ul не может содержать что-то кроме li

2020-01-31 08:04 UTC, SergeyPechinov requested changes

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +      <a class="credit" href="#" ></a>
они не ведут на другую страницу, а только меняют заголовок и текст ниже, поэтому не должны быть ссылками

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +      <h3 class="design-Life-Kids"> Design Life Kids </h3>
в названиях классов не должно быть больших букв

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +    </section>
почему он не в main?

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +           </button>
1. Не является элементом навигации
2. Вообще не правильно сделан(всего 5 звезд), каждая звезда должна быть кнопкой, и текста "Company Rating:" нет

> при нажатии на определенную звезду будет ставиться рейтинг компании

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +         <a class="footer-navigation" href="#"> Copyright © 2018 Dlk • Design Life Kids </a>
это не ссылка, это просто текст

2020-01-31 08:04 UTC, SergeyPechinov commented on index.html
> +        <a class="footer-navigation" href="#"> Web Design — Direct Line Development </a>
1 и 2 колонка обернуты в секцию, а 3-я почему-то нет

2020-02-05 14:30 UTC, Aleksandr-dl commented
я вроде все исправил, кроме оценки сайта, подскажи, а то что то не понял, пожалуйста

2020-03-15 11:33 UTC, merged